# AgentInit MCP Configuration
# Generated automatically by agentinit

# --- MCP Server Definitions ---
[mcp_servers.context7]
command = "npx"
args = [ "-y", "@upstash/context7-mcp", "--api-key=YOUR_API_KEY" ]

[mcp_servers.supabase]
command = "npx"
args = [
  "-y",
  "@supabase/mcp-server-supabase@latest",
  "--read-only",
  "--project-ref=abc123"
]

[mcp_servers.supabase.env]
  SUPABASE_ACCESS_TOKEN = "token123"

[mcp_servers.notion_api]
url = "https://mcp.notion.com/mcp"

[mcp_servers.notion_events]
url = "https://mcp.notion.com/sse"

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"

[mcp_servers.github.headers]
  Authorization = "Bearer YOUR_GITHUB_PAT"
